# Generated by Django 6.0 on 2025-12-12 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulte', models.CharField(choices=[('FACILE', 'Facile'), ('MOYENNE', 'Moyenne'), ('DIFFICILE', 'Difficile')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('FEMME', 'Femme'), ('HOMME', 'Homme')], max_length=10)),
                ('age', models.IntegerField()),
                ('poids', models.FloatField(help_text='Poids en kg')),
                ('taille', models.FloatField(help_text='Taille en cm')),
                ('niveau_sportif', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='appAthlet.athlete')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='appAthlet.exercice')),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='appAthlet.sport'),
        ),
    ]
