# Generated by Django 6.0 on 2025-12-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAthlet', '0002_alter_exercice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='description',
            field=models.TextField(),
        ),
    ]
