# Generated by Django 6.0 on 2025-12-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appAthlet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('score_precision', models.FloatField(help_text='Score de précision IA (0-1 ou %)')),
                ('recommandations', models.TextField(blank=True)),
                ('session_exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_ia', to='appAthlet.sessionexercice')),
            ],
        ),
    ]
